version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: student-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'Leela@2005'
      MYSQL_DATABASE: leela
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: ./fullstack-back
    container_name: student-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/leela?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Leela@2005
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      mysql-db:
        condition: service_healthy

  frontend:
    build:
      context: ./fullstack-front
    container_name: student-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data:
